### ISSUE TITLE
Adding Visual Studio extension category into Monaca

### ISSUE THREAD

**Issue by masahirotanaka** [OnsenUI/project-templates#10]
@frankdiox 

I've got a feedback from Khemry if we can move Onsen UI to our own category.
The category can be named like "Monaca/Onsen UI".
What do you think?

**Comment by frandiox** [comment]
@masahirotanaka  Do you mean that Onsen UI should be displayed under Monaca instead of Apache Cordova Apps in VS2015?
I'm not sure if that would increase or decrease visibility, but I think the difference would not be big. And I guess it's a way to connect Monaca and Onsen UI in VS, so we can do it if you want.

**Comment by masahirotanaka** [comment]
Yes, please modify when you have time. It's lower priority. Thanks.
